name: scheduled_scraping
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0,6,12,18 * * *'
  push:
    branches: [main]

#should be noted that xvfb and google-chrome are already installed in the default github runner

jobs:
  run_scraper:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v3

        - name: Cache Database
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache
          DB_CACHE_NUMBER: 0
        with:
          path: ~/tiny_db_dir
          key:
            env.DB_CACHE_NUMBER

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('un_scraping_conda_env.yml') }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('un_scraping_conda_env.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: conda_setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: un_scraping
          environment-file: un_scraping_conda_env.yml
          auto-activate-base: false
          use-only-tar-bz2: true
      - name: conda_info_display
        run: |
          conda env list
          conda activate un_scraping
          conda info
          conda list

      - name: debug display chrome version 2
        run: |
          google-chrome --version
          whereis google-chrome

      - name: Run headless scraper
        run: |
          sudo apt-get -y install xvfb
          xvfb-run python . --adblocker_dir adblocker_extension --db_dir ~/tiny_db_dir --chrome_version "`google-chrome --version`"
