name: scheduled_scraping
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0,6,12,18 * * *'




jobs:
  # android_lint:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3

  #     - name: Set up JDK 11
  #       uses: actions/setup-java@v3
  #       with:
  #         java-version: 11
  #         distribution: temurin
  #         cache: gradle

  #     - name: android lint
  #       run: ./gradlew lint

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: android-lint-report
  #         path: ~/app/build/reports/lint-results.html

  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: android-lint-report
  #         path: ./**/build/reports/lint-results.xml
